import type { Metadata } from 'next'

export const SITE_URL = 'https://gestivio.ca'

export type Locale = 'fr' | 'en'

interface BuildMetadataOptions {
  title: string
  description: string
  path?: string // e.g. '/blog/mon-article' (no trailing slash)
  locale?: Locale
  image?: string
  keywords?: string[]
  noIndex?: boolean
  type?: 'website' | 'article'
  publishedAt?: string
  authors?: string[]
}

// Builds a consistent Metadata object with canonical + hreflang + OG + Twitter tags.
// The path should NOT include the domain. Alternates for the other locale are
// auto-generated by prefixing with '/en' or '/fr' — adjust `altPath` if your
// routing uses different conventions.
export function buildMetadata({
  title,
  description,
  path = '/',
  locale = 'fr',
  image = '/og-default.png',
  keywords,
  noIndex,
  type = 'website',
  publishedAt,
  authors,
}: BuildMetadataOptions): Metadata {
  const canonical = `${SITE_URL}${path}`
  const imgUrl = image.startsWith('http') ? image : `${SITE_URL}${image}`

  const frPath = locale === 'fr' ? path : path.replace(/^\/en/, '') || '/'
  const enPath = locale === 'en' ? path : `/en${path === '/' ? '' : path}`

  return {
    title,
    description,
    keywords,
    alternates: {
      canonical,
      languages: {
        'fr-CA': `${SITE_URL}${frPath}`,
        'en-CA': `${SITE_URL}${enPath}`,
        'x-default': `${SITE_URL}${frPath}`,
      },
    },
    robots: noIndex ? { index: false, follow: false } : undefined,
    openGraph: {
      type,
      locale: locale === 'fr' ? 'fr_CA' : 'en_CA',
      alternateLocale: locale === 'fr' ? 'en_CA' : 'fr_CA',
      url: canonical,
      siteName: 'Gestivio',
      title,
      description,
      images: [{ url: imgUrl, width: 1200, height: 630, alt: title }],
      ...(type === 'article' && publishedAt ? { publishedTime: publishedAt } : {}),
      ...(authors ? { authors } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [imgUrl],
    },
  }
}
